CarsTest/Models/Car.cs
using System.ComponentModel.DataAnnotations;

namespace CarsTest.Models
{
    public class Car
    {
        private int _carId;
        private string _model;
        private int _year;      
        private string _imagePath;
        [Required]
        [StringLength(32, ErrorMessage = "Model cannot be longer than 32 characters.")]
        public string Model
        {
            get { return _model; }
            set { _model = value; }
        }
        [Required]
        [Range(1950, 2017, ErrorMessage = "Range must be between 1950 and 2017")]
        public int Year
        {
            get { return _year; }
            set { _year = value; }
        }

        public string ImagePath
        {
            get { return _imagePath; }
            set { _imagePath = value; }
        }

        [Key]
        public int CarId
        {
            get { return _carId; }
            private set { _carId = value; }
        }

    }
}

CarsTest/Models/File.cs
using System.ComponentModel.DataAnnotations;

namespace CarsTest.Models
{
    public class File
    {
        [StringLength(255)]
        public string FileName { get; set; }
        [StringLength(100)]
        public string ContentType { get; set; }
        public byte[] Content { get; set; }
    }
}

CarsTest/Controllers/CarController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CarsTest.Models;
using CarsTest.DAL;

namespace CarsTest.Controllers
{
    public class CarController : Controller
    {
        private readonly CarsContext _db = new CarsContext();
        private static string _tmpPath;


        public ActionResult Index()
        {
            return View(_db.Cars.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = _db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CarId,Model,Year,ImagePath")] Car car, HttpPostedFileBase upload)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        car.ImagePath = string.Format("Content/Images/{0}", upload.FileName);
                    }
                    else
                    {
                        car.ImagePath = "Content/Images/images.png";
                    }
                    _db.Cars.Add(car);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("",
                    "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(car);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = _db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            _tmpPath = car.ImagePath;
            return View(car);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CarId,Model,Year,ImagePath")] Car car, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    car.ImagePath = string.Format("Content/Images/{0}", upload.FileName);
                }
                else
                    car.ImagePath = _tmpPath;
                _db.Entry(car).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(car);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = _db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Car car = _db.Cars.Find(id);
            _db.Cars.Remove(car);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CarsTest/Views/Car/Create.cshtml
@model CarsTest.Models.Car

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Car", null, FormMethod.Post, new {enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Car</h4>
        <hr/>
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Model, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model)
                @Html.ValidationMessageFor(model => model.Model)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year)
                @Html.ValidationMessageFor(model => model.Year)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Image", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class ="btn-default" type="file" id="Photo" name="upload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarsTest/Views/Car/Delete.cshtml
@model CarsTest.Models.Car

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Car</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CarsTest/Views/Car/Details.cshtml
@model CarsTest.Models.Car

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Car</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            Image
        </dt>

        <dd>
            <img src="@Url.Content("../../" + Model.ImagePath)" height="100" width="150" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CarId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CarsTest/Views/Car/Edit.cshtml
@model CarsTest.Models.Car

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Car", null, FormMethod.Post, new {enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Car</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.CarId)

        <div class="form-group">
            @Html.LabelFor(model => model.Model, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model)
                @Html.ValidationMessageFor(model => model.Model)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year)
                @Html.ValidationMessageFor(model => model.Year)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Image", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content("../../" + Model.ImagePath)" height="100" width="150"/>
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Change image", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="btn-default" type="file" id="Photo" name="upload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarsTest/Views/Car/Index.cshtml
@model IEnumerable<CarsTest.Models.Car>

<h2>List of cars</h2>

<table class="table table-responsive">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Year)
        </th>
        <th>
            Image
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                <img src="@Url.Content(item.ImagePath)" height="100" width="150"/>
                <!--@Html.DisplayFor(modelItem => item.ImagePath)-->
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {id = item.CarId}) |
                @Html.ActionLink("Details", "Details", new {id = item.CarId}) |
                @Html.ActionLink("Delete", "Delete", new {id = item.CarId})
            </td>
        </tr>
    }

</table>
<hr/>
<p>
    @Html.ActionLink("Create New", "Create")
</p>

CarsTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - List of Cars</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Hrechukh Task</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>